kind: Service
apiVersion: v1
metadata:
  name:  aineko
spec:
  selector:
    name:  aineko
    app: aineko-front
  type:  NodePort
  ports:
  - name:  web
    nodePort: 30165
    port:  80
    targetPort:  80