apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  aineko-front
  labels:
    name:  aineko
    app: aineko-front
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  aineko-front
    spec:
      containers:
      - image:  coderpews/aineko-front:release-1.0.0
        name:  aineko-front
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "512m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
          - name: profile
            valueFrom:
              configMapKeyRef:
                name: settings-config
                key: PROFILE
        ports:
        - containerPort:  80
          name:  web
  