apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  aineko-settings
  labels:
    name:  settings
    app: aineko-settings
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  aineko-settings
    spec:
      containers:
      - image:  coderpews/aineko-settings:release-1.0.3
        name:  aineko-settings
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "512m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /site/
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /site/
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
          - name: profile
            valueFrom:
              configMapKeyRef:
                name: settings-config
                key: PROFILE
          - name: DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: postgres
                key: CONNECTION_STRING
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: DB_PASSWORD 
        ports:
        - containerPort:  8080
          name:  web
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always